package NekosGo

type NSFW string
type SFW string

const (
	RandomHentaiGIF NSFW = "/img/Random_hentai_gif"
	Pussy           NSFW = "/img/pussy"
	NekoGIF         NSFW = "/img/nsfw_neko_gif"
	LewdNeko        NSFW = "/img/lewd"
	Lesbian         NSFW = "/img/les"
	Kuni            NSFW = "/img/kuni"
	CumSluts        NSFW = "/img/cum"
	Classic         NSFW = "/img/classic"
	Boobs           NSFW = "/img/boobs"
	BJ              NSFW = "/img/bj"
	Anal            NSFW = "/img/anal"
	Avatar          NSFW = "/img/nsfw_avatar"
	Yuri            NSFW = "/img/nsfw_avatar"
	Trap            NSFW = "/img/trap"
	Tits            NSFW = "/img/tits"
	GirlSoloGIF     NSFW = "/img/solog"
	GirlSolo        NSFW = "/img/solo"
	PussyWankGIF    NSFW = "/img/pwankg"
	PussyArt        NSFW = "/img/pussy_jpg"
	Kemonomimi      NSFW = "/img/lewdkemo"
	Kitsune         NSFW = "/img/lewdk"
	Keta            NSFW = "/img/keta"
	Holo            NSFW = "/img/hololewd"
	HoloEro         NSFW = "/img/holoero"
	Hentai          NSFW = "/img/hentai"
	Futanari        NSFW = "/img/futanari"
	Femdom          NSFW = "/img/femdom"
	FeetGIF         NSFW = "/img/feetg"
	EroFeet         NSFW = "/img/erofeet"
	Feet            NSFW = "/img/feet"
	Ero             NSFW = "/img/ero"
	EroKitsune      NSFW = "/img/erok"
	EroKemonomimi   NSFW = "/img/erokemo"
	EroNeko         NSFW = "/img/eron"
	EroYuri         NSFW = "/img/eroyuri"
	CumArts         NSFW = "/img/cum_jpg"
	BlowJob         NSFW = "/img/blowjob"
	Spank           NSFW = "/img/spank"
	Gasm            NSFW = "/img/gasm"
)

const (
	Tickle                        SFW = "/img/tickle"
	Slap                          SFW = "/img/slap"
	Poke                          SFW = "/img/poke"
	Pat                           SFW = "/img/pat"
	Neko                          SFW = "/img/neko"
	Meow                          SFW = "/img/meow"
	Lizard                        SFW = "/img/lizard"
	Kiss                          SFW = "/img/kiss"
	Hug                           SFW = "/img/hug"
	FoxGirl                       SFW = "/img/fox_girl"
	Feed                          SFW = "/img/feed"
	Cuddle                        SFW = "/img/cuddle"
	SFWNekoGIF                    SFW = "/img/ngif"
	SFWKemonomimi                 SFW = "/img/kemonomimi"
	SFWHolo                       SFW = "/img/holo"
	Smug                          SFW = "/img/smug"
	Baka                          SFW = "/img/baka"
	Woof                          SFW = "/img/woof"
	Wallpaper                     SFW = "/img/wallpaper"
	Goose                         SFW = "/img/goose"
	GeneticallyEngineeredCatGirls SFW = "/img/gecg"
	SFWAvatar                     SFW = "/img/avatar"
	Waifu                         SFW = "/img/waifu"
)
