package NekosGo

type NSFWImage string
type SFWImage string

type NSFWGif string
type SFWGif string

const (
	// Images
	PeeingLewd      NSFWImage = "peeing_lewd"
	KetaLewd        NSFWImage = "keta_lewd"
	AnalLewd        NSFWImage = "anal_lewd"
	YiffLewd        NSFWImage = "yiff_lewd"
	KemonomimiLewd  NSFWImage = "kemonomimi_lewd"
	YuriEro         NSFWImage = "yuri_ero"
	PantyhoseEro    NSFWImage = "pantyhose_ero"
	PiersingLewd    NSFWImage = "piersing_lewd"
	AllTagsEro      NSFWImage = "all_tags_ero"
	AllTagsLewd     NSFWImage = "all_tags_lewd"
	AhegaoAvatar    NSFWImage = "ahegao_avatar"
	SoloLewd        NSFWImage = "solo_lewd"
	BdsmLewd        NSFWImage = "bdsm_lewd"
	ShinobuEro      NSFWImage = "shinobu_ero"
	KitsuneLewd     NSFWImage = "kitsune_lewd"
	HoloLewd        NSFWImage = "holo_lewd"
	WallpaperLewd   NSFWImage = "wallpaper_lewd"
	KemonomimiEro   NSFWImage = "kemonomimi_ero"
	HPlayEro        NSFWImage = "hplay_ero"
	PiersingEro     NSFWImage = "piersing_ero"
	YuriLewd        NSFWImage = "yuri_lewd"
	EroWallpaperEro NSFWImage = "ero_wallpaper_ero"
	HoloAvatar      NSFWImage = "holo_avatar"
	NekoLewd        NSFWImage = "neko_lewd"
	FeetLewd        NSFWImage = "feet_lewd"
	KitsuneEro      NSFWImage = "kitsune_ero"
	FeetEro         NSFWImage = "feet_ero"
	CumLewd         NSFWImage = "cum_lewd"
	HoloEro         NSFWImage = "holo_ero"
	TitsLewd        NSFWImage = "tits_lewd"
	ClassicLewd     NSFWImage = "classic_lewd"
	ShinobuLewd     NSFWImage = "shinobu_lewd"
	SmallBoobsLewd  NSFWImage = "small_boobs_lewd"
	BlowjobLewd     NSFWImage = "blowjob_lewd"
	KetaAvatar      NSFWImage = "keta_avatar"
	PussyLewd       NSFWImage = "pussy_lewd"
	CosplayLewd     NSFWImage = "cosplay_lewd"
	FutanariLewd    NSFWImage = "futanari_lewd"
	TrapLewd        NSFWImage = "trap_lewd"
	PantyhoseLewd   NSFWImage = "pantyhose_lewd"
	FemdomLewd      NSFWImage = "femdom_lewd"
	AnusLewd        NSFWImage = "anus_lewd"
	NekoEro         NSFWImage = "neko_ero"

	// Gif
	FeetGif      NSFWGif = "feet"
	CumGif       NSFWGif = "cum"
	GirlsSoloGif NSFWGif = "girls_solo"
	TitsGif      NSFWGif = "tits"
	BlowjobGif   NSFWGif = "blow_job"
	PussyWankGif NSFWGif = "pussy_wank"
	PussyGif     NSFWGif = "pussy"
	YuriGif      NSFWGif = "yuri"
	NekoGif      NSFWGif = "neko"
	YiffGif      NSFWGif = "yiff"
	SpankGif     NSFWGif = "spank"
	KuniGif      NSFWGif = "kuni"
	ClassicGif   NSFWGif = "classic"
	AnalGif      NSFWGif = "anal"
	AllTagsGif   NSFWGif = "all_tags"
)

const (
	// Images
	Smug              SFWImage = "smug"
	EightBall         SFWImage = "8ball"
	NekoAvatarsAvatar SFWImage = "neko_avatars_avatar"
	Gecg              SFWImage = "gecg"
	Holo              SFWImage = "holo"
	Lizard            SFWImage = "lizard"
	Neko              SFWImage = "neko"
	NoTagAvatar       SFWImage = "no_tag_avatar"
	HoloAvatarSFW     SFWImage = "holo_avatar"
	Kitsune           SFWImage = "kitsune"
	Wallpaper         SFWImage = "wallpaper"
	Waifu             SFWImage = "waifu"
	KetaAvatarSFW     SFWImage = "keta_avatar"
	Cat               SFWImage = "cat"
	Kimononawa        SFWImage = "kimononawa"
	Shinobu           SFWImage = "shinobu"

	// Gif
	SmugGif    SFWGif = "smug"
	CuddleGif  SFWGif = "cuddle"
	SlapGif    SFWGif = "slap"
	PatGif     SFWGif = "pat"
	PokeGif    SFWGif = "poke"
	FeedGif    SFWGif = "feed"
	NekoGifSFW SFWGif = "neko"
	BakaGif    SFWGif = "baka"
	HugGif     SFWGif = "hug"
	KissGif    SFWGif = "kiss"
	TickleGif  SFWGif = "tickle"
)
